---
- name: Configure Apache httpd.conf (lineinfile - legacy).
  lineinfile:
    dest: "{{ apache_server_root }}/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  with_items: "{{ apache_ports_configuration_items }}"
  when: item.line is defined
  notify: restart apache

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts | bool


- name: Remove apache vhosts configuration.
  file:
    path: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    state: absent
  notify: restart apache
  when: not apache_create_vhosts | bool
